

DROP DATABASE IF EXISTS rosemary;
CREATE DATABASE rosemary DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE rosemary;

CREATE TABLE cliente (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR (255),
telefone VARCHAR (255),
cpf VARCHAR (255),
email VARCHAR(255),
senha VARCHAR(255),
data_nasc VARCHAR(255)
);

CREATE TABLE perfume (
id INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR (255),
marca VARCHAR (255),
descricao VARCHAR (10000),
sexo VARCHAR(255),
preco DECIMAL(10,2),
quant VARCHAR (255),
imagem1 VARCHAR(255),
tipo varchar(255),
durabilidade VARCHAR(50),
notas VARCHAR(255),
intensidade VARCHAR(50),
ocasiao VARCHAR(50),
estacao VARCHAR(50),
favorito BOOLEAN DEFAULT 0
);

CREATE TABLE respostas_formulario (
    id INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cliente_email VARCHAR(255),
    cliente_id INT(10),
    perfume_id INT(10),
    estacao VARCHAR(50),
    sexo VARCHAR(50),
    intensidade VARCHAR(50),
    notas VARCHAR(255),
    ocasiao VARCHAR(50),
    durabilidade VARCHAR(50),
    FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE CASCADE,
    FOREIGN KEY (perfume_id) REFERENCES perfume(id) ON DELETE CASCADE,
    INDEX idx_cliente_id (cliente_id),
    INDEX idx_perfume_id (perfume_id)
);

CREATE TABLE favoritos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_email VARCHAR(255),
    cliente_id INT,
    perfume_id INT,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id),
    FOREIGN KEY (perfume_id) REFERENCES perfume(id),
    CONSTRAINT unique_favorito UNIQUE (cliente_email, cliente_id, perfume_id)
) ENGINE=InnoDB;

CREATE TABLE comentarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    email VARCHAR(255),
    comentario TEXT,
    id_perfume INT,
    resposta TEXT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_perfume) REFERENCES perfume(id) ON DELETE CASCADE
);

CREATE TABLE pedido (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cliente_id INT,
    cliente_email varchar(255),
    total DECIMAL(10,2),
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE itens_pedido (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    pedido_id INT,
    perfume_id INT,
    quantidade INT,
    preco_unitario DECIMAL(10,2),
    FOREIGN KEY (pedido_id) REFERENCES pedido(id),
    FOREIGN KEY (perfume_id) REFERENCES perfume(id)
);



INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Chanel N5','Chanel','feminino', 1160.00 , './img/chanel.png', 'importadof', 'Duradouro', 'Notas Cítricas', 'Intenso', 'Ambos', 'Inverno', 'Chanel N°5 evoca um aroma floral indefinido que sobrevive à passagem das tendências fugazes. Um clássico da perfumaria mundial, para a mulher que esbanja sensualidade e romantismo. Um bouquet de flores abstractas com uma feminilidade indefinível. Com notas encantadoras de ylang-ylang e neroli, desenvolvendo-se então com jasmim de Grasse e rosa de Maio. Uma composição inesquecível, que termina com madeira de Sandalo e Baunilha, fundindo-se na pele, exibindo assim as lembranças mais queridas, secretas e sensuais de uma mulher.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Good Girl','Carolina Herrera','feminino', 589.00, './img/good.webp', 'importadof', 'Duradouro', 'Oriental (Notas Silvestres)', 'Intenso', 'Noturno', 'Outono', 'As doces, surpreendentes e fascinantes qualidades do jasmim trazem ao Good Girl o brilho da feminilidade. O lado misterioso do Good Girl é expresso pelo rico aroma do cacau e pela energia do cumaru, enquanto a amêndoa e o café trazem notas de uma ousada vivacidade. Como a própria cidade de Nova York, Good Girl é audaz, poderosa e ousada. Em um local onde tudo é possível. O perfume Good Girl empodera as mulheres para que conquistem a cidade sem nunca deixarem sua essência de lado. Com os sapatos certos, uma mulher pode conquistar o mundo.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Light Blue','Dolce & Gabbana','feminino', 429.00, './img/blue.jpg', 'importadof', 'Leve e Discreto', 'Floral Frutado (Notas Cítricas)', 'Suave', 'Diurno', 'Verão', 'Light Blue é um Perfume Dolce & Gabbana feminino floral frutado. Ideal para mulheres modernas que gostam do estilo de vida elegante e casual, já que traduz o sol intenso e as noites deslumbrantes revelando toda a sensualidade do Mediterrâneo. O Perfume Light Blue, convida você a um passeio de iate pela costa italiana, onde você poderá expressar toda a sua sensualidade e alegria. O cedro siciliano alia-se à frescura da maçã verde e à sedução e espontaneidade floral da campainha, em que a nota de saída capta a essência de um verão solarengo no sul da Itália. Feminina e determinada, a frescura do bambu é suavizada por um bouquet feminino de jasmim e rosa branca.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Coco Mademoiselle','Chanel','feminino', 1160.00, './img/mademoiselle.jpg', 'importadof', 'Duradouro', 'Oriental (Notas Silvestres)', 'Intenso', 'Ambos', 'Primavera', 'Com uma fragrância enérgica e voluptuosa, Chanel Coco Mademoiselle Eau de Parfum captura a essência de uma mulher audaciosa e livre. Um oriental feminino de personalidade forte e um frescor surpreendente. A fragrância abre com notas refrescantes de Laranja, Mandarina, Bergamota e Flor de Laranjeira. No coração, um buquê sensual de Rosa Turca, Jasmim, Mimosa e Ylang Ylang. Por fim, o rastro desdobra as nuances de Patchouli, Almíscar Branco, Baunilha, Vetiver, Fava Tonka e Opoponax.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Jadore','Dior','feminino', 479.00, './img/jadore.jpg', 'importadof', 'Duradouro', 'Floral Frutado (Notas Tropicais)', 'Intenso', 'Ambos', 'Primavera', 'Jadore é um perfume Dior feminino floral. Um verdadeiro buquê de flores, desenvolvido a partir de finas essências para expressar sensualidade e frescor. O Perfume Jadore Dior é precioso como ouro líquido, e reflete essa inspiração luminosa nas notas de flores nobres que compõem a fragrância. O Ylang-ylang das Ilhas Comores no topo é o toque exótico do perfume Jadore Dior, o coração de Rosa Damascena possui sensualidade, já o fundo composto pelo par de Jasmim Sambac e Jasmim de Grasse são luxuosos e voluptuosos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('La Vie Est Belle','Lancôme','feminino', 743.00, './img/belle.jpg', 'importadof', 'Duradouro', 'Oriental (Notas Tropicais)', 'Suave', 'Ambos', 'Outono', 'La Vie Est Belle é um perfume buquê floral Gourmand da Lancôme, considerado a essência da felicidade. A fragrância é uma verdadeira declaração de alegria encapsulada em um sorriso de cristal. Imagine-se imersa em uma atmosfera de alegria e feminilidade vibrante, onde cada nota celebra a beleza da vida. Essa é a magia do La Vie Est Belle, uma fragrância emblemática que envolve seus sentidos e eleva sua alma, transportando-a para um mundo de pura plenitude.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Elysee Nuit','O Boticário','feminino', 279.00, './img/elysee.jpg', 'oboticariof', 'Duradouro', 'Oriental Floral (Notas Silvestres)', 'Intenso', 'Noturno', 'Inverno', 'Elysee Nuit Eau de Parfum exala ousadia em todos os sentidos. Seu ar moderno mistura a sofisticação do chypre com a jovialidade do gourmand, criando uma fragrância única na perfumaria feminina.  Combina Rosas Damascenas colhidas antes do amanhecer, momento em que exalam sua melhor fragrância, e o toque adocicado do Macaron, um tradicional doce francês. Este Eau de Parfum integra a família olfativa Chypre Gourmand, envolvido por notas de saída de Flor de Ameixa, Cassis, Frutas Vermelhas e Bergamota.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Glamours Secrets','O Boticário','feminino', 134.90, './img/glamour.jpg', 'oboticariof', 'Leve e Discreto', 'Floral Frutado (Notas Cítricas)', 'Suave', 'Ambos', 'Primavera', 'Liz, uma fragrância feminina intensa e marcante, traduz o poder das madeiras combinado à delicadeza e sensualidade de um floral arrebatador. Sua assinatura é a exclusiva Base de Laire Iris Nobre — uma fórmula secreta que traz a união do óleo da sofisticada Íris Absoluta Francesa com a força do Vetiver de Madagascar. Para desenvolver Liz, a perfumista francesa Emilie Copperman se inspirou na sensualidade e força feminina. A combinação entre o amadeirado e o floral é perfeita para mulheres que buscam fragrâncias com personalidade e potência, sem deixar de lado o toque de dulçor e frescor envolventes.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Coffee Womam','O Boticário','feminino', 179.80, './img/coffee.jpg', 'oboticariof', 'Duradouro', 'Oriental (Notas Tropicais)', 'Intenso', 'Ambos', 'Outono', 'Coffee Woman Seduction Desodorante Colônia é uma fragrância irresistível, sensual e doce. Sua fórmula carrega o equilíbrio entre Madeira e Musk, a intensidade do óleo essencial dos grãos de Café Arábica e a sensualidade das notas frutais com delicado toque floral. Tudo isso agregado a notas delicadas e quentes de Chocolate Branco, para entregar uma fragrância doce e intensa ao mesmo tempo. Com perfumação sensual, viciante, irresistível e memorável, a embalagem de Coffee Woman Seduction Desodorante Colônia busca referências no café, apresentando uma curvatura semelhante a de seus grãos, com cor vibrante e intensa para te acompanhar todos os dias.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Egeo Dolce','O Boticário','feminino', 129.90, './img/egeo.jpg', 'oboticariof', 'Leve e Discreto', 'Oriental Floral (Notas Tropicais)', 'Suave', 'Ambos', 'Verão', 'Egeo Dolce Desodorante Colônia traz a mesma doçura que você já conhece em uma nova embalagem jovial, colorida e cheia de personalidade! O Egeo feminino é tão irresistível quanto um doce! Com uma combinação de cheiros adocicados, ela é perfeita para mulheres que querem seduzir com um toque de diversão.  O desodorante colônia feminino pertence à família olfativa Oriental Gourmand, que tem como característica perfil olfativo açucarado. O Egeo Dolce Desodorante Colônia traz a combinação de cheiros do Marshmallow, Sorvete de Framboesa, Algodão-Doce e da Baunilha para vocês se divertir e curtir todas as possibilidades como se não houvesse amanhã. Se você gosta de fragrâncias femininas doces, aposte nesse que é um dos grandes sucessos da perfumaria do Boticário.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Floratta Blue','O Boticário','feminino', 129.90, './img/floratta.jpg', 'oboticariof', 'Leve e Discreto', 'Floral Frutado (Notas Frutas Vermelhas)', 'Suave', 'Diurno', 'Primavera', 'A fragrância feminina do Floratta Red Desodorante Colônia é inspirada na flor da Maçã de Vermont.  A fragrância traz a delicadeza da flor da maçã e a doçura do fruto. Além de notas de saída de Frutas Vermelhas e Laranja.  O corpo do Floratta Red é puro floral. Uma combinação de Flor de Laranjeira, Violeta, Flor de Lótus, Tuberosa e Flor de Beijo. Já as notas de base, que deixam o rastro da fragrância, trazem Chocolate Amargo, Musk, Sândalo, Cedro e Âmbar.  O Floratta Red Desodorante Colônia é uma fragrância feminina marcante, jovem e envolvente que combina com mulheres de atitude que não passam vontade no romance!'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Lily','O Boticário','feminino', 279.90, './img/lily.jpg', 'oboticariof', 'Duradouro', 'Floral (Notas Silvestres)', 'Suave', 'Ambos', 'Primavera', 'Ele traz uma fragrância sofisticada mais fresca que transborda feminilidade, ideal para te acompanhar no dia a dia. Inspirado na mulher que pode ser tão empoderada quanto sensível, L’eau de Lily Desodorante Colônia conta com um toque de frescor e delicadeza em uma assinatura floral e marcante. L’eau de Lily é uma fragrância que tem alta fixação e deixa rastro por onde passa. Agora você pode sentir as facetas únicas dessa fragrância feminina da família olfativa Floral  na pele. A essência de uma mulher leve e marcante!'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Una Artisan','Natura','feminino', 269.00, './img/una.jpg', 'naturaf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Ambos', 'Outono', 'Uma fragrância chipre floral autêntica, como uma peça feita à mão. A costura perfeita entre flores e madeiras quentes ganha um toque cremoso de baunilha e cassis. Enriquecido com priprioca, ingrediente natural da biodiversidade brasileira, Natura Una Artisan exala beleza e elegância. Sua fórmula contém morango, amora selvagem, bergamota, sândalo, musk e priprioca, ingrediente natural da biodiversidade brasileira.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Luna Intenso','Natura','feminino', 116.90, './img/luna.jpg', 'naturaf', 'Duradouro', 'Oriental (Notas Silvestres)', 'Intenso', 'Ambos', 'Inverno', 'A versão mais intensa do chipre característico de Luna, agora realçada no Luna Intenso. Descubra a identidade do primeiro Deo Parfum Natura, e experimente uma fragrância única e sensual. Combinando uma dose generosa do patchouli mais potente e puro com notas gourmand de baunilha, o Luna Intenso Natura é ainda mais realçado com uma seleção única de florais femininos e notas cremosas aveludadas de pêssego, garantindo uma experiência incrível.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Ilía Secreto','Natura','feminino', 159.90, './img/ilia.jpg', 'naturaf', 'Leve e Discreto', 'Floral Frutado (Notas Frutas Vermelhas)', 'Suave', 'Ambos', 'Primavera', 'A cremosidade das flores brancas contrasta com notas adocicadas de fava tonka, um acorde de frutas roxas e um toque exclusivo de café arábica. Uma fragrância enriquecida com Ishpink, ingrediente da biodiversidade Amazônica que provoca os sentidos e guarda os segredos da força feminina. Descubra sua essência secreta com o Deo Parfum Ilía Secreto feminino em uma fragrância que provoca os sentidos!'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Essencial Elixir','Natura','feminino', 139.90, './img/essencial.jpg', 'naturaf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Noturno', 'Inverno', 'Uma poderosa combinação de flor de muguet e bergamota com notas amadeiradas de patchouli e um toque inusitado de pripioca, ingrediente natural da biodiversidade brasileira. Uma fragrância chipre que exala sofisticação e feminilidade. Essencial Elixir Traz o frescor de notas cítricas e frutais com um corpo floral, finalizado pelo patchouli. Ideal para mulheres modernas, seguras e confiantes. Uma fragrância exclusiva que garante uma perfumação inesquecível.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Meu Primeiro Humor','Natura','feminino', 134.90, './img/humor.jpg', 'naturaf', 'Leve e Discreto', 'Floral Frutado (Notas Frutas Vermelhas)', 'Suave', 'Ambos', 'Verão', 'A fragrância frutal de Meu Primeiro Humor é uma forma única de encarar a vida, convidando-nos a quebrar a seriedade do cotidiano de maneira ousada e divertida: um aroma que convida a espalhar alegria. A combinação de notas cítricas e um coquetel de frutas vibrantes, contrastados com um irresistível toque de frozen de pera, resulta em uma fragrância irreverente. Enriquecida com priprioca, um ingrediente natural da biodiversidade brasileira, a fragrância Primeiro Humor é o primeiro e inconfundível queridinho da linha.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Kriska','Natura','feminino', 129.90, './img/kriska.jpg', 'naturaf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Noturno', 'Outono', 'Kriska Drama Natura é a fragrância ideal para momentos ousados e femininos, graças a sua combinação única de notas adocicadas de nozes carameladas, açúcar derretido, amendoim e avelãs torradas. Seja para uma noite especial ou para expressar sua personalidade marcante no dia a dia, Kriska Drama é uma ótima escolha, se destacando pela cremosidade das favas de baunilha e as notas amadeiradas, que acrescentam uma profundidade envolvente.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Eudora Parfum','Eudora','feminino', 209.90, './img//eudora.jpg', 'eudoraf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Ambos', 'Inverno', 'Eudora Eau De Parfum, o famoso "Eudora Roxo" entrega uma fragrância sofisticada e intensa, com notas repletas de personalidade. Foi criado para mulheres que são donas de um poder de atração único, capazes de instigar, provocar e conquistar de uma forma poderosamente feminina. A combinação floral sensual carrega especiarias selecionadas que traduzem a assinatura de mulheres inesquecíveis. Ideal para as ocasiões mais especiais, Eudora Eau de Parfum é marcante na pele e nos melhores momentos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Kiss me','Eudora','feminino', 139.90, './img/kiss.jpg', 'eudoraf', 'Leve e Discreto', 'Oriental Floral (Notas Frutas Vermelhas)', 'Suave', 'Ambos', 'Verão', 'Colônia Desodorante Kiss Me Roxo Impulso é inspirada nas cores mais amadas dos batons de Eudora. Uma explosão de cores transformada em uma fragrância vibrante, alegre, feminina e delicada. Colônia Desodorante Kiss Me Roxo Impulso possui uma combinação deliciosa, trazendo o doce e a suculência das frutas de forma leve nessa criação, perfeita para ser sua próxima fragrância favorita.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Diva','Eudora','feminino', 120.00, './img/diva.jpg', 'eudoraf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Noturno', 'Outono', 'Inspirado no poder que toda mulher carrega dentro de si, Diva Esplêndida é uma fragrância feminina que celebra o despertar da sua diva interior e convida você a vivê-la ao máximo! Da família olfativa Oriental Floral, o desodorante colônia feminino traz uma fragrância esplêndida. Ela combina o toque vibrante da Bergamota e da calda de Framboesa aliada a um Bouquet Floral poderoso para enriquecer a sua rotina de perfumação. Além das notas de Íris, Gardênia e Ylang-ylang que compõem o Bouquet Floral, a fragrância também conta com o toque marcante e inconfundível da Baunilha e do Sândalo que assina esse olfativo e intensifica o seu brilho único.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Instance','Eudora','feminino', 79.99, './img/instance.jpg', 'eudoraf', 'Leve e Discreto', 'Oriental Floral (Notas Cítricas)', 'Suave', 'Ambos', 'Primavera', 'Colônia Desodorante Instance é o novo oriental frutal que veio para dar potência à feminilidade tão presente no seu dia a dia. Uma combinação de notas florais, frutas suculentas e a cremosidade da baunilha, envolvida pelo conforto do sândalo, finalizam esta criação única e feminina. Colônia Instance é uma fragrância delicada e presente, que veio para te levar a lugares inesquecíveis, assim como é para quem a sente.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Rouge','Eudora','feminino', 159.90, './img/rouge.jpg', 'eudoraf', 'Duradouro', 'Oriental Floral (Notas Frutas Vermelhas)', 'Suave', 'Ambos', 'Primavera', 'Eudora Rouge Eau de Parfum foi criado de forma exclusivamente para mulheres de atitude, que provocam reações ao passar e permanecem na memória daqueles que cruzam o seu caminho.Com inspiração no poder e na confiança que o vermelho desperta, Eudora criou um Eau de Parfum elegante e que marca presença. Sua essência marcante, combina as notas suculentas da Maçã Vermelha e Ameixa com a personalidade da Flor de Jasmim. A intensidade das notas amadeiradas de Patchouli e o Segredo de Eudora tornam esta fragrância feminina ainda mais inesquecível.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('La Victorie','Eudora','feminino', 164.90, './img/aurien.webp', 'eudoraf', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Intenso', 'Ambos', 'Inverno', 'Desde sempre, a relação entre mulheres e joias é algo inexplicável. Por isso, Colônia Desodorante Aurien Gold buscou inspiração na alta joalheria internacional e interpreta a pureza do ouro, o metal mais nobre e desejado pelas mulheres de todo o mundo! Uma fragrância floral amadeirada marcante que exala luxo e brilho. Seu brilho intenso reflete uma personalidade tão exuberante e iluminada quanto o ouro. A nobreza das flores é realçada pela Íris Branca e a preciosidade do Caviar de Baunilha de Madagascar. O acorde Ouro e o exclusivo Segredo de Eudora trazem ainda mais personalidade para essa criação.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Eliana Cristal','Jequiti','feminino', 119.90, './img/eliana.jpg', 'jequitif', 'Leve e Discreto', 'Floral Frutado (Notas Cítricas)', 'Suave', 'Diurno', 'Verão', 'Eliana Shine, é a nova fragrância da artista, inspirada em mulheres de personalidade e com feminilidade exuberante. É uma joia com embalagem luxuosa, espetacular e única. A colônia combina notas cítricas na saída, com um refinado bouquet floral e com a cremosidade da amêndoa, resultando na sofisticada criação da moderna perfumaria mundial. Eliana Shine, única como uma fragrância, brilhante como uma joia.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Adriane Galisteu','Jequiti','feminino', 146.00, './img/adriane.jpg', 'jequitif', 'Duradouro', 'Oriental Floral (Notas Tropicais)', 'Suave', 'Ambos', 'Primavera', 'Assinada por Adriane Galisteu, a exclusiva fragrância traduz a modernidade, estilo e autenticidade de uma celebridade. Provocante mistura de frutas vermelhas exóticas, combinadas à um buque e envolventes notas de camurça que dão opulência e personalidade à fragrância.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Cláudia Leitte ','Jequiti','feminino', 151.90, './img/claudia.jpg', 'jequitif', 'Leve e Discreto', 'Floral Frutado (Notas Frutas Vermelhas)', 'Suave', 'Diurno', 'Verão', 'A sofisticação de uma estrela. O provante jasmim do Egito e as Rosas da Turquia oferecem glamour à fragrância. Notas vibrantes de gengibre e bergamota são envolvidas delicadamente pelo patchouli.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Amore','Jequiti','feminino', 49.90, './img/amore.png', 'jequitif', 'Duradouro', 'Floral (Notas Silvestres)', 'Suave', 'Ambos', 'Primavera', 'Mulher romântica de forma clássica. Delicada como uma flor, ela ama intensamente e expressa sua feminilidade. Sua fragrância traz reginadas notas amadeiradas combinadas a femininas notas florais com um toque de baunilha. Jequiti Amore, romance que aflora e renova os sentidos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Sabrina Sato','Jequiti','feminino', 85.90, './img/sabrina.png', 'jequitif', 'Duradouro', 'Oriental Floral (Notas Frutas Vermelhas)', 'Intenso', 'Ambos', 'Verão', 'Autêntica e fashionista, Sabrina Sato tem uma sensualidade única, é extrovertida e conquista a todos pelo seu carisma e simpatia. Sua fragrância revela muita feminilidade através de um bouquet floral cremoso, nuances vibrantes de frutas e um fundo amadeirado de amberwood e cashmeran que tornam a criação robusta e elegante. Sabrina Sato seu lado autêntico e único.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Patrícia Abravanel','Jequiti','feminino', 139.90, './img/patricia.png', 'jequitif', 'Leve e Discreto', 'Floral Frutado (Notas Cítricas)', 'Suave', 'Ambos', 'Primavera', 'Patricia Abravanel irradia luz por onde passa. Alegre e espontânea, ela é uma inspiração dentro e fora das telas. Uma mulher determinada, que esbanja felicidade e que transmite um momento de muito sucesso em sua vida, suas celebrações e conquistas. Sua fragrância traz a alegria das frutas combinada as delicadas notas florais e o lado adocicado das notas de praline e baunilha. Patricia Abravanel Joy irreverente, espontânea e cheia de atitude.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('One Million','Pacco Rabanne','Masculino', 489.00, './img/paco.jpg', 'importadom', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Esta edição de colecionador exalta a lendária fragrância do Eau de Toilette de One Million.Este aroma de couro fresco e picante combina notas de cabeça de pomelo, hortelã e laranja sanguínea para criar um coquetel luminoso e reluzente. Canela e absoluto de rosa fornecem intensidade e virilidade no coração. Por fim, mas não menos importante, o acorde final de couro blond, madeira branca, âmbar e patchouli tornam esta fragrância uma mistura sensual e irresistível.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('CH Men Prive','Carolina Herrera','Masculino', 629.00, './img/ch.jpg', 'importadom', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Noturno', 'Outono', 'CH Men Prive é um perfume oriental, arborizado, com couro, emocionante, rico e luxuoso. A composição combina camadas de acordes de explosivos: Na fragrância de CH Men Privé as notas quentes e luxuriantes de uísque e couro preto, intenso e sensual, são realçadas. Ele abre com acordes cítricos de grapefruit, pomelo e uísque que levam ao coração da lavanda congelado, sálvia, tomilho vermelho e cardamomo. As notas de base são de couro, fava tonka e benjoim.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Dark Rebel','John Varvatos','Masculino', 347.00, './img/john.jpg', 'importadom','Duradouro', 'Oriental Amadeirado', 'Intenso', 'Noturno', 'Outono', 'Dark Rebel de John Varvatos é uma fragrância intensa e marcante, inspirada no couro preto e no frio urbano de Detroit. A fragrância Dark Rebel, criado por Rodrigo Flores-Roux, abre com notas ousadas de Rum, Cana de açúcar, Artemísia, Cardamomo e Sálvia Esclaréia. No coração, um toque intenso de Couro, Resina de Abeto, Styrax e Pimenta. Por fim, uma combinação inesquecível de Folha de Tabaco, Baunilha Mexicana, Castóreo, Akigalawood, Notas Amadeiradas e Zimbro'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Gucci Intence Oud','Aurelien Guichard','Masculino', 264.00, './img/gucci.jpg', 'importadom', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Noturno', 'Inverno', 'Esta fragrância é uma mistura intensa e sofisticada que capta a essência exótica e luxuosa da madeira oud. O perfume abre com notas ricas e esfumaçadas de incenso e couro, criando uma aura cativante e misteriosa. As notas de coração revelam a madeira de oud profunda e sedutora, acrescentando um elemento de opulência e sensualidade. A fragrância é ancorada pelas notas de fundo de âmbar e patchouli, proporcionando um final quente e convidativo. Gucci Intense Oud EDP Spray for Men é uma fragrância poderosa e duradoura que exala confiança e requinte.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Coach For Men','Dior','Masculino', 589.00, './img/coach.jpg', 'importadom', 'Duradouro', 'Amadeirado Especiado', 'Ambos', 'Primavera', 'Primavera', 'O perfume masculino Coach For Men evoca um feeling confiante e cool, e traduz em aroma a atitude de Nova Iorque e a autenticidade americana. A fragrância inicia com notas enérgicas de bergamota, Kumquat (fruto) e pera verde Nashi, um tipo asiático que dá um toque efervescente para a fragrância. Uma explosão picante de cardomomo adiciona calor, complexidade e uma pitada sutil de doçura ao coração, que recebe ainda acordes de gerânio e coentro. Em suas notas de fundo, o perfume possui uma base texturizada de vetiver, camurça e âmbar cinza.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Bleu Chanel','Chanel','Masculino', 880.00, './img/bleu.jpg', 'importadom', 'Duradouro', 'Amadeirado Aromático', 'Ambos', 'Primavera', 'Primavera', 'O retrato deste amadeirado aromático é um tributo à liberdade masculina. Uma composição atemporal e anticonformista dentro de um frasco misterioso azul. A fragrância de Chanel Bleu incorpora a exaltação do homem que busca a liberdade de viver, recusa o lugar-comum e não se prende as regras. A composição de chanel blue revela o espírito do homem que decide e busca o seu destino com foco e determinação.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Arbo Botanic','O Boticário','Masculino', 172.80, './img/arbo.jpg', 'oboticariom', 'Duradouro', 'Aromático Fresco', 'Suave', 'Ambos', 'Verão', 'Arbo Botanic acredita que uma dose diária de natureza energiza. Por isso, buscou no movimento das Florestas Urbanas e no verde das folhas da Costela-de-Adão, a inspiração para criar esta fragrância masculina fresca e potente.   A sua fragrância traz o revigorante acorde ENERGY, composto pela Sálvia, ingrediente comprovado pela neurociência por despertar a sensação de energia que a natureza proporciona. Integrante do portfólio de perfumaria masculina do Boticário, Arbo Botanic Desodorante Colônia é perfeito para que você que quer sentir a natureza mais próximo de você o tempo todo.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Malbec Bleu','O Boticário','Masculino', 189.90, './img/malbec.jpg', 'oboticariom', 'Duradouro', 'Amadeirado Especiado', 'Intenso','Ambos', 'Inverno', 'Sendo a primeira fragrância da linha Malbec e a mais querida entre os homens, traz como inspiração o mundo dos vinhos para a perfumaria masculina. O álcool vínico, obtido através da fermentação da uva, é envelhecido em barris de carvalho francês, iguais àqueles em que descansam os melhores vinhos do mundo.  Este Desodorante Colônia combina com qualquer ocasião, envolvendo seu corpo e sua rotina com notas amadeiradas quentes que combinam o frescor frutal a nuances especiadas, dando origem a uma fragrância masculina inesquecível, mais seca e menos adocicada, marca registrada de Malbec.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Quasar Ice','O Boticário','Masculino', 144.90, './img/quasar.jpg', 'oboticariom', 'Duradouro', 'Aromático Aquático', 'Suave', 'Ambos', 'Verão', 'Quase Ice Desodorante Côlonia é da família olfativa Fougère Aldeídica e possui uma fragrância com frescor extremo. Ainda conta com um ingrediente inovador e sustentável que transforma resíduos da produção de papel Pinus FSC em uma dose extra de refrescância, assim como a sensação do vento frio extremo que sopra no alto das montanhas geladas.  O item da perfumaria masculina é ideal para quem adora se cuidar e proteger a natureza.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Celebre Sua Força','O Boticário','Masculino', 86.00, './img/celebre.jpg', 'oboticariom', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Celebre Sua Força Desodorante Colônia Masculino, traz uma fragrância fresca, potente e perfeita para nos lembrar de quanto é importante celebrar as pequenas conquistas do dia a dia. O segredinho desse desodorante colônia é a sua fragrância masculina do jeito que você gosta. Da família olfativa Fougère Aromático, ela traz o frescor das notas cítricas contrastadas com o brilho das especiarias e a intensidade das madeiras secas. Ideal para te acompanhar na sua rotina de autocuidado.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Malbec Vert','O Boticário','Masculino', 189.90, './img/vert.jpg', 'oboticariom', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Malbec Vert é um Amadeirado Fresco Aromático único, desenvolvido através de um processo de fabricação exclusivo no mundo, com álcool vínico envelhecido em barris de carvalho francês, que foge do óbvio e consegue ser marcante e refrescante ao mesmo tempo. Para desenvolver essa fragrância masculina, o Boticário combinou o álcool vínico, característico do marcante DNA de Malbec, e as uvas congeladas do Ice Wine, trazendo pela primeira vez uma fragrância marcante, porém com um frescor'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Coffe Man','O Boticário','Masculino', 179.90, './img/coffeeman.jpg', 'oboticariom', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Coffee Man Fusion Desodorante Colônia foi feita para homens sofisticados, que permitem ousar discretamente com uma perfumação inovadora. Sendo da família Oriental Ambarada, essa fragrância masculina carrega essências marcantes e sedutoras do oriente. Já as notas ambaradas são responsáveis pelo calor dessa fragrância.  Foi na sobremesa italiana Tiramissu que encontramos a inspiração de ingredientes para criar as fragrâncias de Coffee Fusion. Cada uma traz um elemento dessa receita para entregar fragrâncias perfeitamente equilibradas. O Coffee Man Fusion Desodorante Colônia traz a mistura de uma dose mais intensa do Café Arábica com o Amaretto, revelando uma nota licorosa e ousada.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('K Deo Parfum','Natura','Masculino', 239.00, './img/naturak.jpg', 'naturam', 'Duradouro', 'Amadeirado Aromático', 'Intenso', 'Noturno', 'Inverno', 'Kaiak K é um Deo Parfum que traz um caminho olfativo inédito no mercado brasileiro: o aromático intenso. Perfeito para homens de espírito livre e aventureiro, que valorizam a intensidade e a durabilidade das fragrâncias, sem abrir mão do frescor, que só o Natura K pode proporcionar.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Essencial Exclusivo','Natura','Masculino', 239.90, './img/essencialmas.jpg', 'naturam', 'Duradouro', 'Amadeirado Especiado', 'Intenso', 'Ambos', 'Outono', 'Essencial Exclusivo é a escolha ideal para homens que desejam deixar sua marca por onde passam. Essa criação moderna e sofisticada combina harmoniosamente a Copaíba, uma madeira da biodiversidade brasileira, com especiarias frescas, como cardamomo e pimenta.  O resultado é uma fragrância amadeirada exclusiva que transforma cada momento em algo verdadeiramente único.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Kaiak Clássico','Natura','Masculino', 99.90, './img/kaiak.jpg', 'naturam', 'Duradouro', 'Amadeirado', 'Intenso', 'Noturno', 'Inverno', 'Kaiak de Natura é um perfume Aromático Fougére Masculino. Kaiak vibra pelo frescor dos cítricos e gálbano, pulsa pela energia aquosa do coração desta fragrância e flui através das madeiras transparentes e musc, se inspirando na energia que emana da sua força.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Sr N','Natura','Masculino', 124.90, './img/srn.jpg', 'naturam', 'Leve e Discreto', 'Aromático', 'Suave', 'Diurno', 'Primavera', 'O Sr N Natura é uma fragrância clássica produzida desde 1979 para o homem que valoriza o tempo. Para isso, conta com uma combinação atemporal das madeiras de patchouli e vetiver em contraste com o frescor cítrico do limão e lavanda.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Biografia','Natura','Masculino', 169.90, './img/biografiamas.jpg', 'naturam', 'Duradouro','Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Com fragrância amadeirada, o Desodorante Colônia Biografia Natura Masculino foi criado para celebrar a história mais importante que existe: a sua. Com uma combinação de notas como sálvia, cedro e sândalo, o Biografia Masculino é uma fragrância versátil, ideal para qualquer ocasião do dia a dia. Por isso, ele pode ser um ótimo presente para alguém especial ou para si mesmo, afinal, todos merecem escrever sua própria biografia com uma fragrância marcante e deliciosa.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Homem Essence','Natura','Masculino', 188.90, './img/homem.jpg', 'naturam', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Natura Homem Essence oferece cuidados para que cada homem se cuide à sua maneira. Uma combinação elaborada, a sofisticada fragrância masculina é esculpida com o coração das madeiras mais nobres como cedro e patchouli, enriquecida com a elegância das notas ambaradas e do cacau, ingrediente natural da biodiversidade brasileira, que envolvem e marcam presença. Para homens que buscam elegância e sofisticação.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Impression Audaz','Eudora','Masculino', 136.44, './img/audaz.jpg', 'eudoram', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Impression Audaz Eau de Parfum é uma fragrância masculina intensa e marcante, que combina OUD, a madeira mais luxuosa do mundo, a notas ambaradas sensuais e de presença profunda.  Este eau de parfum masculino é um Amadeirado Oriental feito para o homem audacioso, inspirador. Suas notas sofisticadas de madeira OUD, considerado o ouro líquido da perfumaria entre os ingredientes, têm ao seu lado a madeira cashmere e o frescor de notas cítricas, resultando em um toque original inovador.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Carbon Turbo','Eudora','Masculino', 164.99, './img/carbon.jpg', 'eudoram', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Noturno', 'Outono', 'Colônia Desodorante Carbon Turbo traz uma fragrância amadeirada intensa e marcante na pele.A linha é inspirada na superação da potência de um motor, na força das pistas, na velocidade do vento, na dedicação do homem que sabe seguir o caminho da conquista. Vencer todos os obstáculos com atitude e traçar sua própria rota com intensidade é Carbon Turbo! A combinação de notas cítricas e aromáticas resulta em uma explosão deliciosa que coloca você em destaque.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Club 6','Eudora','Masculino', 104.99, './img/club.jpg', 'eudoram', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Colônia Desodorante Club 6 Vip traz uma fragrância marcante com mistura de madeiras nobres, pimentas sensuais e um toque de couro, para o homem que gosta de exclusividade. Perfeito para o homem intenso e sedutor, que aproveita ao máximo tudo o que a vida tem a lhe oferecer. A combinação de notas amadeiradas e notas apimentadas traduzem a sensualidade dessa fragrância exclusiva.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('For Life','Eudora','Masculino', 119.90, './img/for.jpg', 'eudoram','Duradouro', 'Oriental Amadeirado', 'Intenso', 'Noturno', 'Outono', 'For Life Desodorante Colônia  é uma fragrância amadeirada que torna a sua presença marcante em todas as ocasiões, principalmente nas mais especiais. Para criar a sintonia perfeita, combina-se ingredientes modernos, picantes. Sua perfumação combina o calor das pimentas com a sensualidade das madeiras em notas envolventes. Suas notas cremosas e cheias de personalidade revelam uma fragrância marcante, destacando ainda mais sua presença.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Rummo Aventura','Eudora','Masculino', 89.99, './img/rummo.jpg', 'eudoram', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Colônia Desodorante Rummo Aventura apresenta uma fragrância fresca, picante e aromática. Nesta colônia, você vai desfrutar na pele todo o frescor das notas aquosas contrastando com toque picante de especiarias e madeira, ideal para quem está sempre preparado para encarar boas aventuras e apostar em novos desafios.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Volpe DNA','Eudora','Masculino', 139.99, './img/volpe.jpg', 'eudoram', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Essa fragrância masculina traz o Óleo de Cipreste, símbolo de força e resistência, que aumenta a sensação de confiança, sentimento essencial para te acompanhar em cada desafio e manter a vontade de vencer em cada obstáculo. Com uma perfumação única e exclusiva, Volpe DNA possui um amadeirado especiado envolvente, feito para atrair a atenção por onde for. As especiarias mescladas com patchouli e cipreste impressionam com notas vibrantes e estimulantes que combinam com a ousadia e originalidade de todo homem Volpe.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Portiolli Celebrate','Jequiti','Masculino', 79.90, './img/portiolli.jpg', 'jequitim', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Portiolli Celebrate 10 Anos de Jequiti é um perfume Âmbar Masculino. Esta é uma nova fragrância. Portiolli Celebrate 10 Anos foi lançada em 2023. O perfumista que assina esta fragrância é Leonardo Lucheze. As notas de topo são: Limão, Lavanda e Pimenta Preta. As notas de coração são: Gerânio, Noz-moscada e Sândalo. As notas de fundo são: Âmbar, Fava Tonka e Cedro.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Carlinhos Maia','Jequiti','Masculino', 79.90, './img/carlinhos.jpg', 'jequitim', 'Leve e Discreto', 'Aromático', 'Suave', 'Diurno', 'Primavera', 'Para a fragrância masculina, oferece uma saída arejada pela presença dos aromáticos sálvia e menta e evolui trazendo a elegante folha de violeta em sintonia com a personalidade inebriante da cumarina. Para finalizar essa criação apostamos em um blend de madeiras poderosas.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('CR7','Jequiti','Masculino', 179.90, './img/CR7.png', 'jequitim', 'Leve e Discreto', 'Aromático', 'Suave', 'Diurno', 'Primavera', 'A fragrância é inspirada em homens autênticos, de bom gosto, que gostam de movimento e aproveitam a vida, assim como o atleta, que também faz sucesso fora do campo. CR7 é um amadeirado vibrante que reúne energia, força e frescor em seus acordes, que refletem o caráter forte e vibrante do ídolo Cristiano Ronaldo.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Champs','Jequiti','Masculino', 89.90, './img/champs.jpg', 'jequitim', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Inverno', 'Uma homenagem aos conquistadores franceses, Jequiti Champs é a essência do homem que constrói sua história. Sua vida, seu campo de triunfo. Vitorioso dos seus próprios desafios. A impactante combinação das notas especiadas e frescas, combinado ao couro e notas amadeiradas dão à fragrância uma personalidade única.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Lamborghini','Jequiti','Masculino', 169.90, './img/lamborghini.jpg', 'jequitim', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Ambos', 'Outono/Inverno', 'Intenso e poderoso, assim como os carros, os perfumes da Lamborghini são objeto de desejo por homens de atitude, sofisticados e amantes de carros. Extremamente impressionante, eles aguçam os desejos e exala todo o poder que uma Lamborghini oferece. Lamborghini, sinônimo de exclusividade e luxo, que cativa os amantes de velocidade. Uma magnífica fragrância que transmite elegância, segurança e bom gosto indispensáveis ao homem moderno.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Malte Reserva','Jequiti','Masculino', 109.90, './img/malte.jpg', 'jequitim', 'Duradouro', 'Amadeirado', 'Intenso', 'Ambos', 'Outono/Inverno', 'Inspirado nos whiskies mais sofisticados, que ficam maturando por 21 anos nos barris de madeira.Essa nova fragrância traz robustez e personalidade com um acorde que combina as notas exclusivas da castanha, caramelo e baunilha dos melhores whiskies. Malte Reserva, para quem faz sua história com personalidade'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Calvin Klein','Calvin Klein','Unissex', 270.90, './img/ck.jpg', 'unissex1', 'Duradouro', 'Cítrico Aromático', 'Suave', 'Ambos', 'Verão', 'CK One é revolucionário e rejeita os estereótipos tradicionais de gênero ao harmonizar o floral feminino com a madeira masculina em uma única fragrância. Atemporal, ousada e clean, sua fragrância reúne notas refrescantes de chá verde e bergamota, perfeitamente equilibradas com nuances de especiarias, como cardamomo, junto às pétalas de rosas e violeta, compondo suas notas de fundo com a sensualidade do musk e do âmbar.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Jo Malone London','Jo Malone London','Unissex', 1175.00, './img/jo.jpg', 'unissex1', 'Duradouro', 'Oriental Especiado', 'Intenso', 'Ambos', 'Verão', 'Um perfume cuja fragrância é um floral frutado. Inspirado na essência do outono, ideal para quem tem um estilo romântico e clássico, mas que também gosta de se sentir envolvente.  O Perfume Jo Malone London, possui uma fragrância frutada com nuances florais. Traz o frescor sensual de peras recolhidas em um buquê de frésias brancas e adoçada pelo âmbar, patchouli e madeiras.  Combina perfeitamente com qualquer ocasião, desde situações do cotidiano até para aqueles momentos mais especiais.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('La Facon','La Facon','Unissex', 219.99, './img/la.jpg', 'unissex1', 'Duradouro', 'Oriental Floral', 'Intenso', 'Ambos', 'Primavera', 'perfume La Façon unissex cítrico floral. Sua fragrância suave e refrescante te transporta para dentro de uma pintura. O Perfume La Façon, buscou no sudoeste da França a inspiração para compor um aroma que exala a imensidão azul das lavandas, das oliveiras e das ruelas medievais que inspiraram artistas como Van Gogh e Monet. Seu perfume abre com a refrescância da Tangerina e Limão Siciliano, explodindo em um encantador coração de Lavanda, finalizando com notas de Musk e Sândalo.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Mémoire d’une Odeur','Gucci','Unissex', 408.00, './img/memoire.jpg', 'unissex1', 'Duradouro', 'Floral Amadeirado',  'Intenso', 'Ambos', 'Primavera', 'sua fragrância tem o poder de explorar memórias, trazendo-as do passado e tornando-as vivas em nosso presente. Viajando para trás e para frente no tempo cronológico, o presente e o passado estão conectados por uma única ponte que projeta diretamente para o futuro. Gucci Mémoire é um elixir que transcende os gêneros por sua individualidade, estabelecendo uma nova família olfativa, a mineral aromática. Mineral, que é uma fusão de aromas e emoções: arejado, almiscarado, transparente e autêntico.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Acqua di Parma','Essenza di Colonia','Unissex', 845.00, './img/acqua.png', 'unissex1', 'Duradouro', 'Cítrico Amadeirado', 'Intenso', 'Ambos', 'Verão', 'Acqua di Parma captura a emocionante sensação de leveza em uma garrafa. Bergamota e limão trazem uma abertura cintilante para a colônia, enquanto notas de rosa e pimenta preta revigoram a ligação brilhante entre o aromático shiso e o alecrim no coração da fragrância. Uma base reconfortante de cedro e almíscar evoca a felicidade interior de passar tempo juntos e criar memórias com seu círculo de amigos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Velvet','Commodity','Unissex', 300.00, './img/velvet.jpg', 'unissex1', 'Duradouro', 'Oriental Amadeirado', 'Suave', 'Ambos', 'Outono', 'Prada Infusion é um perfume unissex floral amadeirado. Elaborado especialmente para homens e mulheres marcantes. Possui fragrância elegante, que deixa uma agradável lembrança por onde passa. Ao mesmo tempo em que possui a leveza do Íris e do Néroli, Prada Infusion DIris Cèdre leva também a intensidade do Benjoim e Incenso, que dão um toque atalcado e acolhedor à fragrância.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Pulse Eudora','Eudora','Unissex', 74.99, './img/pulse.jpg', 'unissex2', 'Duradouro', 'Floral Frutado', 'Suave', 'Ambos', 'Primavera', 'O caminho para o sucesso pode ser cheio de desafios, mas com uma fragrância que exala força e confiança, você estará preparado para encarar qualquer obstáculo com elegância. Este desodorante colônia possui notas frescas e ao mesmo tempo envolventes, como o Cedro, a Lavanda e o Âmbar Elemi. Uma combinação estimulante e criativa, ideal para acompanhar você no dia a dia, seja em uma reunião de trabalho ou em um momento à dois.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Humor Liberta','Natura','Unissex', 139.90, './img/liberta.jpg', 'unissex2', 'Duradouro', 'Floral Frutado', 'Intenso', 'Ambos', 'Verão', 'Natura Humor Liberta se inspirou no espírito livre de uma geração que não abre mão de ser feliz e convida todos a levar a vida com mais leveza. Humor Liberta é uma nova fragrância para todo mundo e propõe um jeito de se perfumar leve e fluido, com notas vibrantes de liberdade. Celebre a liberdade.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Quasar Drop','O Boticário','Unissex', 144.90, './img/drop.jpg', 'unissex2', 'Duradouro', 'Cítrico Aquático', 'Suave', 'Ambos', 'Verão', 'Quasar Drop XX Desodorante Colônia  foi feito para quem busca intensidade e coragem e isso reflete em sua embalagem e fragrância, que possuem muita personalidade. Quasar Drop XX é uma grande inovação Fougére Floral unissex, pois ainda não existia esse tipo de fragrância. A grande inspiração para essa criação foi o universo do skate e todo o movimento que existe nesse lifestyle. O Boticário foi buscar em grandes centros cheiros que traduzem a verdadeira adrenalina e força da vida urbana e chegou em uma fragrância unissex fresca e leve.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Alchemists','O Boticário','Unissex', 379.90, './img/alchemists.jpg', 'unissex2', 'Duradouro', 'Oriental Amadeirado', 'Intenso', 'Ambos', 'Outono', 'Alchemists do Boticário é sinônimo de sofisticação e exclusividade, uma verdadeira obra de arte da alta perfumaria.  Combina notas frutais de Lichia, Framboesa e Musk. A Rosa de Maio, considerada a rainha de todas as flores, é o segredinho dessa fragrância. Essa rosa floresce apenas uma vez por ano, durante a primavera e é colhida uma a uma no Sul da França e no Vale das Rosas na Bulgária para a extração do seu óleo essencial.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Calma a Alma','O Boticário','Unissex', 99.90, './img/calma.jpg', 'unissex2', 'Duradouro', 'Floral Amadeirado', 'Suave', 'Ambos', 'Primavera', 'Aroma & Terapia Calma na Alma Desodorante Colônia possui uma fragrância da família olfativa Floral Cítrico com ingredientes que além de perfumar a pele, ajudam a melhorar a sensação de bem-estar. Perfeito para promover sensação de conforto, relaxamento e tranquilidade.  O desodorante colônia proporciona uma experiência olfativa que tem todos esses benefícios comprovados por meio de testes científicos, como a neurociência.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Prada Infusion','O Boticário','Unissex', 109.90, './img/insensatez.jpg', 'unissex2', 'Duradouro', 'Floral Amadeirado', 'Intenso', 'Ambos', 'Primavera', 'Dispensando rótulos, Insensatez Desodorante Colônia é perfeita para pessoas originais que não buscam se enquadrar no pensamento comum e acreditam que as diferenças nos unem.   Agradável por seu frescor, combina o delicado toque de flores como Rosa, Violeta e Jasmim, à intensidade da madeira e notas cítricas de Tangerina e Abacaxi. Além disso, é um produto vegano'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Granado','Granado','Infantil', 70.00, './img/granado.jpg', 'infantil1', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'A Colônia Bebê Lavanda traz o conforto e a naturalizada desta planta em uma fragrância relaxante. Sua fórmula suave tem base aquosa (não contém álcool) e foi especialmente desenvolvida para refrescar e perfumar a delicada pele do bebê. Indicada para todas as faixas etárias, inclusive recém-nascidos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Giovanna Baby','Giovanna Baby','Infantil', 139.90, './img/giovanna.jpg', 'infantil1', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'A Colônia Giovanna Baby Classic é composta pelo Óleo Essencial de Lavanda acompanhado harmoniosamente de Bouquet Floral que mescla a delicadeza da Rosa Chá à feminilidade do Jasmim e o frescor do Muguet. A nota de fundo é encorpada pelo Sândalo com um exclusivo toque de Musk.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Mamãe e Bebê','Natura','Infantil', 49.90, './img/bebe.jpg', 'infantil1', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'A Colônia de Mamãe e Bebê traz aconchego e cuidado em uma fragrância levemente cítrica, que combina flores suaves de lavanda com notas levemente adocicadas. A fragrância da Água de Colônia Mamãe e Bebê para deixar o seu bebê com cheirinho de amor e carinho. Experimente agora!'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Dr Botica','O Boticário','Infantil', 84.90, './img/botica.jpg', 'infantil1', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'Com a mesma fragrância icônica da linha de cabelos, inspirada na Maçã Verde Dr. Botica 1982, a colônia infantil é da família olfativa Floral Frutado. Ela carrega notas de Maçã Verde e Jasmim que combinam com o conforto do Musk. Ideal para acompanhar a vida dos pequenos a partir de 3 anos, trazendo aventuras próximas à natureza. Dr. Botica Poção da Aventura Colônia, inspira a trazer novas aventuras e conexão com a natureza.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Johnsons','Johnsons','Infantil', 48.99, './img/johnsons.jpg', 'infantil1', 'Duradouro', 'Lavanda', 'Suave', 'Diurno', 'Primavera/Verão', 'Colônia Lavanda para bebês ajuda a manter seu bebê perfumado e fresquinho entre um banho e outro, com um cheirinho de banho tomado. Pele delicadamente perfumada, com frescor natural de lavanda. Dermatologicamente testado e é livre de parabenos e ftalatos; a aplicação do produto no bebê deixa sua pele delicadamente perfumada.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Eudora Kids','Eudora','Infantil', 61.99, './img/kids.jpg', 'infantil1', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'Eudora Kids Era Uma Vez Colônia Infantil é feita para tornar os seus momentos com os pequenos ainda mais especiais. A Colônia faz parte da família olfativa Floral Musk e revela uma fragrância suave e delicada, desenvolvida especialmente para crianças de 3 a 6 anos. É a escolha perfeita para perfumar e proteger a pele dos pequenos.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Huggies','Huggies','Infantil', 20.79, './img/huggies.jpg', 'infantil2', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'A Colônia Huggiesda linha Extra Suave foi especialmente desenvolvida para perfumar a pele e as roupinhas do bebê. Sua fórmula exclusiva é dermatologicamente testada, sem álcool etílico e não irrita a pele.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Petit','Avon','Infantil', 32.49, './img/petit.jpg', 'infantil2', 'Duradouro', 'Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'A fragrância clássica e leve de Petit em uma embalagem alegre e romântica. Petit Attitude apresenta o frescor da brisa marinha misturado com notas frutais suculentas e notas florais românticas, que trazem a alegria e a atitude que toda menina precisa.'); 
INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Bvlgari','Bvlgari','Infantil', 364.99, './img/bvlgari.jpg', 'infantil2', 'Duradouro', 'Cítricas, Florais', 'Suave', 'Diurno', 'Primavera/Verão', 'Bvlgari Petits Et Mamans é um perfume floral amadeirado almiscarado e é a primeira fragrância a ser criada para crianças. Criado pelo perfumista Nathalie Lorson, a fragrância tem no seu topo notas de laranja siciliana, bergamota e Pau-Brasil.'); 


-- INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Musti','Mustela','Infantil', 112.90, './img/musti.jpg', 'infantil2', '', '', '', '', '', ''); 
-- INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Care Baby','Avon','Infantil', 25.99, './img/care.jpg', 'infantil2', '', '', '', '', '', ''); 
-- INSERT INTO perfume (nome, marca, sexo, preco, imagem1, tipo, durabilidade, notas, intensidade, ocasiao, estacao, descricao) VALUES ('Tous Baby','Carolina Herrera','Infantil', 589.00, './img/tous.jpg', 'infantil2', '', '', '', '', '', ''); 